from __future__ import annotations

from .artifacts import (
    SOFTWARE_CHANGE_REPLAY_REPORT_CORPUS_CLAUSE_LOCATOR,
    SOFTWARE_CHANGE_REPLAY_REPORT_CORPUS_IDENTIFIER,
    SOFTWARE_CHANGE_REPLAY_REPORT_CORPUS_SHA256,
    SOFTWARE_CHANGE_REPLAY_REPORT_CORPUS_URI,
    SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_CLAUSE_LOCATOR,
    SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_IDENTIFIER,
    SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_PATH,
    SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_SHA256,
    SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_URI,
    SOFTWARE_CHANGE_REPLAY_REPORT_PROCEDURE_CLAUSE_LOCATOR,
    SOFTWARE_CHANGE_REPLAY_REPORT_PROCEDURE_IDENTIFIER,
    SOFTWARE_CHANGE_REPLAY_REPORT_PROCEDURE_SHA256,
    SOFTWARE_CHANGE_REPLAY_REPORT_PROCEDURE_URI,
    VERDICT_INTEROP_CORPUS_CLAUSE_LOCATOR,
    VERDICT_INTEROP_CORPUS_IDENTIFIER,
    VERDICT_INTEROP_CORPUS_SHA256,
    VERDICT_INTEROP_CORPUS_URI,
    VERDICT_INTEROP_PROCEDURE_CLAUSE_LOCATOR,
    VERDICT_INTEROP_PROCEDURE_IDENTIFIER,
    VERDICT_INTEROP_PROCEDURE_SHA256,
    VERDICT_INTEROP_PROCEDURE_URI,
    reference_profile_builtin_verdict_interop_artifact_set,
    reference_profile_software_change_replay_report_corpus_dependency,
    reference_profile_software_change_replay_report_procedure_dependency,
    reference_profile_verdict_interop_artifact_set,
    reference_profile_verdict_interop_corpus_dependency,
    reference_profile_verdict_interop_procedure_dependency,
)
from .declarations import (
    AGENT_ADMISSION_VERDICT_INTEROP_PACKAGE_CLASS,
    reference_profile_agent_admission_verdict_interop_declaration,
)
from .model import (
    ReferenceProfileConformanceArtifactSet,
    ReferenceProfileVerdictInteropDeclaration,
)

__all__ = [
    "AGENT_ADMISSION_VERDICT_INTEROP_PACKAGE_CLASS",
    "SOFTWARE_CHANGE_REPLAY_REPORT_CORPUS_CLAUSE_LOCATOR",
    "SOFTWARE_CHANGE_REPLAY_REPORT_CORPUS_IDENTIFIER",
    "SOFTWARE_CHANGE_REPLAY_REPORT_CORPUS_SHA256",
    "SOFTWARE_CHANGE_REPLAY_REPORT_CORPUS_URI",
    "SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_CLAUSE_LOCATOR",
    "SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_IDENTIFIER",
    "SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_PATH",
    "SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_SHA256",
    "SOFTWARE_CHANGE_REPLAY_REPORT_DECLARATION_URI",
    "SOFTWARE_CHANGE_REPLAY_REPORT_PROCEDURE_CLAUSE_LOCATOR",
    "SOFTWARE_CHANGE_REPLAY_REPORT_PROCEDURE_IDENTIFIER",
    "SOFTWARE_CHANGE_REPLAY_REPORT_PROCEDURE_SHA256",
    "SOFTWARE_CHANGE_REPLAY_REPORT_PROCEDURE_URI",
    "VERDICT_INTEROP_CORPUS_CLAUSE_LOCATOR",
    "VERDICT_INTEROP_CORPUS_IDENTIFIER",
    "VERDICT_INTEROP_CORPUS_SHA256",
    "VERDICT_INTEROP_CORPUS_URI",
    "VERDICT_INTEROP_PROCEDURE_CLAUSE_LOCATOR",
    "VERDICT_INTEROP_PROCEDURE_IDENTIFIER",
    "VERDICT_INTEROP_PROCEDURE_SHA256",
    "VERDICT_INTEROP_PROCEDURE_URI",
    "ReferenceProfileConformanceArtifactSet",
    "ReferenceProfileVerdictInteropDeclaration",
    "reference_profile_agent_admission_verdict_interop_declaration",
    "reference_profile_builtin_verdict_interop_artifact_set",
    "reference_profile_software_change_replay_report_corpus_dependency",
    "reference_profile_software_change_replay_report_procedure_dependency",
    "reference_profile_verdict_interop_artifact_set",
    "reference_profile_verdict_interop_corpus_dependency",
    "reference_profile_verdict_interop_procedure_dependency",
]
